const express = require('express');
const multer = require('multer');
const { authenticate } = require('../middleware/auth');
const auth = require('../controllers/authController');
const claims = require('../controllers/claimController');
const env = require('../config/env');
const router = express.Router();
router.post('/auth/login', auth.login);
router.get('/health', (req,res)=>res.json({ status:'ok', service:'claims-api', time:new Date().toISOString() }));
router.get('/health/ai', async (req,res,next)=>{ try { res.json(await require('../services/aiService').health()); } catch(e){ next(e); } });
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: env.maxDocumentBytes } });
router.use('/api', authenticate);
router.get('/api/claims', claims.list);
router.get('/api/claims/:id', claims.get);
router.patch('/api/claims/:id/status', claims.updateStatus);
router.post('/api/claims/:id/documents', upload.single('document'), claims.upload);
router.post('/api/claims/:id/generate-assessment', claims.assessment);
router.get('/api/policies/search', claims.searchPolicies);
module.exports = router;
